version: 2.0.{build}

skip_branch_with_pr: true
os: Visual Studio 2017

cache:
  - packages -> paket.lock
  - '%LocalAppData%\NuGet\Cache'
  - '%LocalAppData%\NuGet\v3-cache'
  - '%UserProfile%\.nuget'

configuration:
  - Debug
  - Release

init:
  - git config --global core.autocrlf true

before_build:
  - .paket\paket.exe restore
  - dotnet restore WTG.Analyzers.sln

build:
  parallel: true
  project: WTG.Analyzers.sln
  verbosity: minimal

after_build:
  - build-packages.cmd %APPVEYOR_BUILD_VERSION%

test:
  assemblies:
    only:
      - '**\*.Test.dll'

artifacts:
  - path: bin\WTG.Analyzers.$(APPVEYOR_BUILD_VERSION).nupkg
  - path: bin\WTG.Analyzers.$(APPVEYOR_BUILD_VERSION).nupkg
