version: 2.0.6.{build}

skip_branch_with_pr: true
os: Visual Studio 2017

cache:
  - packages -> paket.lock
  - '%LocalAppData%\NuGet\Cache'
  - '%LocalAppData%\NuGet\v3-cache'
  - '%UserProfile%\.nuget'

configuration:
  - Debug
  - Release

environment:
  WTG_ANALYZERS_VERSION: 2.0.6

init:
  - git config --global core.autocrlf true

before_build:
  - .paket\paket.exe restore
  - dotnet restore WTG.Analyzers.sln

build:
  parallel: true
  project: WTG.Analyzers.sln
  verbosity: minimal

after_build:
  - build-packages.cmd %WTG_ANALYZERS_VERSION% %APPVEYOR_REPO_COMMIT%

test:
  assemblies:
    only:
      - '**\*.Test.dll'

artifacts:
  - path: bin\WTG.Analyzers.$(WTG_ANALYZERS_VERSION).nupkg
  - path: bin\WTG.Analyzers.Utils.$(WTG_ANALYZERS_VERSION).nupkg
  - path: bin\WTG.Analyzers.TestFramework.$(WTG_ANALYZERS_VERSION).nupkg

deploy:
  - provider: NuGet
    api_key:
      secure: 'N0UpuDdHhEWIREEAXYDSNqJqpNIBq5c5lcIvpoAzvQA5A7AdCH2/l/b4VNWipmLk'
    skip_symbols: false
    artifact: /.*\.nupkg/
    on:
      configuration: Release
      appveyor_repo_tag: true
