//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class ClassyBob 	 
{
	public void Bob()  // comment
	{
		// comment 
		Barry();    
	}
	
	void Barry()			
	{
	}
} 
