//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class Bob
{
	private string PrivateField;
	private string PrivateProperty => PrivateField;
	private string PrivateMethod() => PrivateField;
	private event EventHandler PublicEvent;
	private class PrivateClass { }
}
