using System.Threading;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using NUnit.Framework;
using WTG.Analyzers.TestFramework;

namespace WTG.Analyzers.Utils.Test
{
	[TestFixture]
	public class SyntaxTreeExtensionsTest
	{
		[TestCase("Barry.cs", ExpectedResult = false)]
		[TestCase("Barry.g.cs", ExpectedResult = true)]
		[TestCase("Barry.Designer.cs", ExpectedResult = true)]
		public async Task<bool> IsGeneratedByFilename(string filename)
		{
			return await Check(filename, "//text").ConfigureAwait(false);
		}

		[TestCase("// Magic", ExpectedResult = false, TestName = "{m} - No marker")]
		[TestCase("// <auto-generated>", ExpectedResult = true, TestName = "{m} - unclosed marker, with dash")]
		[TestCase("// <autogenerated>", ExpectedResult = true, TestName = "{m} - unclosed marker, no dash")]
		[TestCase("// <auto-generated />", ExpectedResult = true, TestName = "{m} - closed marker, with dash")]
		[TestCase("// <autogenerated />", ExpectedResult = true, TestName = "{m} - closed marker, no dash")]
		public async Task<bool> IsGeneratedByContent(string content)
		{
			return await Check("Barry.cs", content).ConfigureAwait(false);
		}

		#region Implementation

		static async Task<bool> Check(string filename, string content)
		{
			using var workspace = ModelUtils.CreateWorkspace();
			var document = workspace
				.CurrentSolution
				.AddProject("Barry", "Barry", LanguageNames.CSharp)
				.AddDocument(filename, SourceText.From(content));

			var tree = await document.GetSyntaxTreeAsync().ConfigureAwait(false);
			return tree.IsGenerated(default);
		}

		#endregion
	}
}
